import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");

function pick(primary, extra, count = 50) {
  const seen = new Set();
  const result = [];
  for (const song of [...primary, ...extra]) {
    const key = `${song.title.toLowerCase()}|${song.artist.toLowerCase()}`;
    if (seen.has(key)) continue;
    seen.add(key);
    result.push(song);
    if (result.length >= count) break;
  }
  return result;
}

const weddingPool = [
  { title: "Polomiću čaše od kristala", artist: "Miroslav Ilić" },
  { title: "Hvala ti za ljubav", artist: "Šaban Šaulić" },
  { title: "Ova svadba najbolja u selu", artist: "Jerina Jović" },
  { title: "Šampionska svadba", artist: "Narodna" },
  { title: "Pevajte pesmu, brat mi se ženi", artist: "Milivoje Karaklajić" },
  { title: "Svadba, svadba", artist: "Dragoslav Mihajlović Kanarinac" },
  { title: "Svatovska pjesma", artist: "Goci Bend" },
  { title: "Srećna ti svadba, brate", artist: "Milivoje Karaklajić" },
  { title: "Kume brate", artist: "Šaban Šaulić" },
  { title: "Danas majko ženiš svoga sina", artist: "Slavko Petrović" },
  { title: "Dajte mi da živim", artist: "Mitar Mirić" },
  { title: "Živela, živela ljubav", artist: "Mitar Mirić" },
  { title: "Kraljice moga srca", artist: "Šaban Šaulić" },
  { title: "Golubica", artist: "Šaban Šaulić" },
  { title: "Dva galeba bela", artist: "Šaban Šaulić" },
  { title: "Op Jano, Jano", artist: "Miroslav Ilić" },
  { title: "Božanstvena ženo", artist: "Miroslav Ilić" },
  { title: "Pozdravi je, pozdravi", artist: "Miroslav Ilić" },
  { title: "Joj Rado joj Radmila", artist: "Miroslav Ilić" },
  { title: "Devojka iz grada", artist: "Miroslav Ilić" },
  { title: "Kleo se kleo", artist: "Snežana Đurišić" },
  { title: "Pričaj mi pričaj", artist: "Snežana Đurišić" },
  { title: "Imena mi mog", artist: "Snežana Đurišić" },
  { title: "Lepi moj", artist: "Snežana Đurišić" },
  { title: "Mirjana", artist: "Tozovac" },
  { title: "Danče", artist: "Tozovac" },
  { title: "Ti si me čekala", artist: "Tozovac" },
  { title: "Oči jedne žene", artist: "Tozovac" },
  { title: "Violino ne sviraj", artist: "Tozovac" },
  { title: "Kafanska pevačica", artist: "Željko Samardžić" },
  { title: "Sve je moje tvoje", artist: "Željko Samardžić" },
  { title: "Slutim", artist: "Željko Samardžić" },
  { title: "Ruzmarin", artist: "Saša Matić" },
  { title: "Samo ovu noć", artist: "Saša Matić" },
  { title: "Lagala je grade", artist: "Saša Matić" },
  { title: "Ko te ljubi ovih dana", artist: "Saša Matić" },
  { title: "Veseljak", artist: "Ana Bekuta" },
  { title: "Zlatiborske zore", artist: "Ana Bekuta" },
  { title: "Zavoleh te", artist: "Ana Bekuta" },
  { title: "Brojanica", artist: "Ana Bekuta" },
  { title: "Duge noge", artist: "Brena" },
  { title: "Sanjam", artist: "Brena" },
  { title: "Uđi slobodno", artist: "Brena" },
  { title: "Dragane moj", artist: "Ceca" },
  { title: "Volim te, tako te ludo volim", artist: "Ceca" },
  { title: "Nagovori", artist: "Ceca" },
  { title: "Mesec nebo zvezdice", artist: "Ceca" },
  { title: "Pitaju me u mom kraju", artist: "Dragana Mirković" },
  { title: "Sto bih cuda ucinila", artist: "Dragana Mirković" },
  { title: "Dajte vina hoću lom", artist: "Haris" },
  { title: "Jesul dunje procvale", artist: "Haris" },
  { title: "Muštuluk", artist: "Haris" },
  { title: "Pusti me, pusti me", artist: "Haris" },
  { title: "Sjećaš li se one noći", artist: "Haris" },
  { title: "Kako mi nedostaješ", artist: "Haris" },
  { title: "Ja bez tebe ne mogu da zivim", artist: "Halid Bešlić" },
  { title: "Prvi poljubac", artist: "Halid Bešlić" },
  { title: "Miris ljiljana", artist: "Halid Bešlić" },
  { title: "Zlatne strune", artist: "Halid Bešlić" },
  { title: "Zbog tebe", artist: "Hanka Paldum" },
  { title: "Crne kose", artist: "Hanka Paldum" },
  { title: "Voljela sam voljela", artist: "Hanka Paldum" },
  { title: "Dunjo moja", artist: "Louis" },
  { title: "Svirajte mi za Željanu", artist: "Ljuba Aličić" },
  { title: "Lepa Maro", artist: "Ljuba Aličić" },
  { title: "Jedina moja", artist: "Marinko Rokvić" },
  { title: "Momak veseljak", artist: "Marinko Rokvić" },
  { title: "Ivana", artist: "Medeni Mesec" },
  { title: "Ljubi me i ništa ne pitaj", artist: "Medeni Mesec" },
  { title: "Medena", artist: "Medeni Mesec" },
  { title: "Manastirska vrata", artist: "Mira Škorić" },
  { title: "Ne može nam niko ništa", artist: "Mitar Mirić" },
  { title: "Jednom kad se zaljubiš", artist: "Mitar Mirić" },
  { title: "Udahni duboko", artist: "Nino" },
  { title: "Usne vrele kao žar", artist: "Nino" },
  { title: "Hej lepoto nad lepotom", artist: "Šaban Šaulić" },
  { title: "Meni je stobom sreca obecana", artist: "Šaban Šaulić" },
  { title: "Hajde srećo moja zakuni se ti", artist: "Šaban Šaulić" },
  { title: "Kafana je moja sudbina", artist: "Toma Zdravković" },
  { title: "Dal je moguće", artist: "Toma Zdravković" },
  { title: "Nevera moja", artist: "Vesna Zmijanac" },
  { title: "Kada bi me pitali", artist: "Zorica Brunclik" },
  { title: "Kosava", artist: "Zorica Brunclik" },
  { title: "Avlije", artist: "Zorica Brunclik" },
  { title: "Đurđevdan", artist: "Bijelo Dugme" },
  { title: "Lipe cvatu", artist: "Bijelo Dugme" },
  { title: "Zenica bluz", artist: "Bijelo Dugme" },
  { title: "Oko moje sanjivo", artist: "Narodna" },
  { title: "Dajte mi vina", artist: "Narodna" },
  { title: "Mili moj", artist: "Narodna" },
  { title: "Čardaš", artist: "Narodna" },
  { title: "Dođi u pet do pet", artist: "Narodna" },
  { title: "Prsten i zlatni lanac", artist: "Narodna" },
  { title: "Kap po kap", artist: "Narodna" },
  { title: "Ne spavaj mala moja", artist: "Narodna" },
  { title: "Hajde da ludujemo ove noći", artist: "Narodna" },
  { title: "Kad zamirišu jorgovani", artist: "Narodna" },
  { title: "Zbog jedne divne crne žene", artist: "Crni Biseri" },
  { title: "Ringišpil", artist: "Crni Biseri" },
  { title: "Brazil", artist: "Crni Biseri" },
  { title: "Dete sreće", artist: "Marko Bulat" },
  { title: "Eno dole u kafani", artist: "Marko Bulat" },
  { title: "Pesma od bola", artist: "Aca Lukas" },
  { title: "Zapišite mi broj", artist: "Aca Lukas" },
  { title: "Bele ruže", artist: "Aca Lukas" },
  { title: "Ne diraj mi noći", artist: "Aco Pejović" },
  { title: "Seti me se jednog dana", artist: "Aco Pejović" },
  { title: "Još te sanjam", artist: "Đani" },
  { title: "Bolje mi je", artist: "Đani" },
  { title: "Ni jedne usne se ne ljube same", artist: "Džej" },
  { title: "Sunce ljubavi", artist: "Džej" },
  { title: "Digni ruku", artist: "Rambo Amadeus" },
  { title: "Mornar", artist: "Rambo Amadeus" },
  { title: "Devojka sa čardaš nogama", artist: "Zdravko Čolić" },
  { title: "Kesten", artist: "Zdravko Čolić" },
  { title: "Mađarica", artist: "Zdravko Čolić" },
  { title: "Ruška", artist: "Zdravko Čolić" },
  { title: "Od zlata jabuka", artist: "Zdravko Čolić" },
  { title: "Samo teraj ti po svome", artist: "Zdravko Čolić" },
  { title: "Motori", artist: "Zdravko Čolić" },
  { title: "Ti si mi u mislima", artist: "Zdravko Čolić" },
  { title: "Takvi kao ti", artist: "Zdravko Čolić" },
  { title: "Moji su drugovi", artist: "Zdravko Čolić" },
  { title: "Zemlja mojih snova", artist: "Zdravko Čolić" },
  { title: "Skeledžijo, skeledžijo", artist: "Narodna" },
  { title: "Ćiribu ćiriba", artist: "Narodna" },
  { title: "Suada", artist: "Narodna" },
  { title: "Igra RnR cela Jugoslavija", artist: "Narodna" },
  { title: "Mjerkam te mjerkam", artist: "Narodna" },
  { title: "To mi radi", artist: "Narodna" },
  { title: "Za ljubav treba imat dušu", artist: "Narodna" },
  { title: "Jedina moja", artist: "Đorđe Balašević" },
  { title: "Oprosti mi što te volim", artist: "Narodna" },
  { title: "Nisam te zbog lepote voleo", artist: "Narodna" },
  { title: "Kao ti", artist: "Narodna" },
  { title: "Esma i ja", artist: "Zdravko Čolić" },
  { title: "Dani su bez broja", artist: "Zdravko Čolić" },
  { title: "Bezobrazno su zelene", artist: "Željko Samardžić" },
  { title: "Gas do daske", artist: "Petar Mitić" },
  { title: "Dođeš mi u san", artist: "Peđa Medenica" },
  { title: "Imam ljubav", artist: "Peđa Medenica" },
  { title: "Nadji novu ljubav", artist: "Saša Matić" },
  { title: "Crveni ruz", artist: "Seka Aleksić" },
  { title: "Hajde da zazmurimo", artist: "Tamara Milutinović" },
  { title: "Zauvek tvoj", artist: "Tropico Bend" },
  { title: "Milimetar", artist: "Željko Joksimović" },
  { title: "Noćas nešto lepo treba da se desi", artist: "Zdravko Čolić" },
  { title: "Anđele", artist: "Zdravko Čolić" },
  { title: "Marina", artist: "Zdravko Čolić" },
  { title: "Mjesečina", artist: "Zdravko Čolić" },
  { title: "Ostani", artist: "Zdravko Čolić" },
  { title: "Dodirni mi kolena", artist: "Zdravko Čolić" },
  { title: "A da je sreće bilo", artist: "Zdravko Čolić" },
  { title: "Učini mi pravu stvar", artist: "Zdravko Čolić" },
  { title: "Majstor za poljupce", artist: "Zdravko Čolić" },
  { title: "Koketa", artist: "Zdravko Čolić" },
  { title: "Amsterdam", artist: "Zdravko Čolić" },
  { title: "Glavo luda", artist: "Zdravko Čolić" },
  { title: "Bosanac", artist: "Zdravko Čolić" },
  { title: "A šta da radim", artist: "Zdravko Čolić" },
  { title: "Napile se ulice", artist: "Zdravko Čolić" },
  { title: "Kreni prema meni", artist: "Zdravko Čolić" },
  { title: "Mladiću moj", artist: "Zdravko Čolić" },
  { title: "Krug", artist: "Zdravko Čolić" },
  { title: "Nataša", artist: "Zdravko Čolić" },
  { title: "Neko te ima noćas", artist: "Zdravko Čolić" },
  { title: "Dolazim za 5 minuta", artist: "Zdravko Čolić" },
  { title: "Vesela pesma", artist: "Bajaga" },
  { title: "Kučka nevjerna", artist: "Zdravko Čolić" },
  { title: "Kada padne noć", artist: "Zdravko Čolić" },
  { title: "Pjevam danju, pjevam noću", artist: "Zdravko Čolić" },
  { title: "Ja bi da pevam jos malo", artist: "Zdravko Čolić" },
  { title: "U ljubav vjerujem", artist: "Parni valjak" },
  { title: "A i ti me izneveri", artist: "Zdravko Čolić" },
  { title: "Daire", artist: "Zdravko Čolić" },
  { title: "Kad sam bio mlad", artist: "Zdravko Čolić" },
  { title: "Ugasi me", artist: "Zdravko Čolić" },
  { title: "Gde si u ovom glupam hotelu", artist: "Zdravko Čolić" },
  { title: "Zeni nam se vukota", artist: "Narodna" },
  { title: "Mi plešemo", artist: "Narodna" },
  { title: "Pusti, pusti modu", artist: "Narodna" },
  { title: "Tempera", artist: "Zdravko Čolić" },
  { title: "Laku noć svirači", artist: "Zdravko Čolić" },
  { title: "Ima nešto od srca do srca", artist: "Zdravko Čolić" },
  { title: "Zato kradem", artist: "Zdravko Čolić" },
  { title: "Da me nije", artist: "Zdravko Čolić" },
  { title: "Laku noć moja barbiko", artist: "Zdravko Čolić" },
  { title: "Da sutis", artist: "Zdravko Čolić" },
  { title: "Ja u ljubav vjerujem", artist: "Zdravko Čolić" },
  { title: "Moji drugovi odavno kuce imaju", artist: "Zdravko Čolić" },
];

const zaMladuPrimary = [
  { title: "Bravo mlada, šećeru", artist: "Vera Matović" },
  { title: "Rekla nana da mi daš", artist: "Snežana Đurišić" },
  { title: "Luckasta si ti", artist: "Miroslav Ilić" },
  { title: "Leno, Leno, Magdaleno", artist: "Tozovac" },
  { title: "Moja mala nema mane", artist: "Zvonko Bogdan" },
  { title: "Devojčice moja mila", artist: "Verica Šerifović" },
  { title: "Pepeljuga", artist: "Verica Šerifović" },
  { title: "Plavokosa devojčica", artist: "Narodna" },
  { title: "Ćero moja mila", artist: "Nada Topčagić" },
  { title: "Ti si ko i ja", artist: "Mira Škorić" },
  { title: "Otkači", artist: "Mira Škorić" },
  { title: "Ne svani zoro mlada", artist: "Mitar Mirić" },
  { title: "Božanstvena ženo", artist: "Miroslav Ilić" },
  { title: "Još te nešto čini izuzetnom", artist: "Miroslav Ilić" },
  { title: "Tebi", artist: "Miroslav Ilić" },
  { title: "Nije život jedna žena", artist: "Miroslav Ilić" },
  { title: "Ja nisam rođena da živim sama", artist: "Ana Bekuta" },
  { title: "Zavoleh te", artist: "Ana Bekuta" },
  { title: "Ostavi mi slobodan stol", artist: "Ana Bekuta" },
  { title: "Beli biseru", artist: "Brena" },
  { title: "Recite mu da ga volim", artist: "Brena" },
  { title: "Hajde da se volimo", artist: "Brena" },
  { title: "Volim te, tako te ludo volim", artist: "Ceca" },
  { title: "Pile", artist: "Ceca" },
  { title: "Lepotan", artist: "Ceca" },
  { title: "Biću njegova", artist: "Dragana Mirković" },
  { title: "Otkad sam se u tebe zaljubila", artist: "Dragana Mirković" },
  { title: "Da si moja devojčica", artist: "Džej" },
  { title: "Zbog tebe", artist: "Hanka Paldum" },
  { title: "Pamtim još", artist: "Hanka Paldum" },
  { title: "Hladno je ugrij me", artist: "Haris" },
  { title: "Laže mjesec", artist: "Haris" },
  { title: "Budi budi uvijek srećna", artist: "Halid Bešlić" },
  { title: "Neću, neću dijamante", artist: "Halid Bešlić" },
  { title: "Žena udata", artist: "Medeni Mesec" },
  { title: "Đavolica", artist: "Medeni Mesec" },
  { title: "Nikad nikom nisam reko", artist: "Medeni Mesec" },
  { title: "Božije suze", artist: "Medeni Mesec" },
  { title: "Šta ću mala stobom", artist: "Nino" },
  { title: "Gordana", artist: "Šaban Šaulić" },
  { title: "Sneg je opet Snežana", artist: "Šaban Šaulić" },
  { title: "Uvenuće narcis beli", artist: "Šaban Šaulić" },
  { title: "Ljepša od noći", artist: "Šako Polumenta" },
  { title: "Dišem za tebe", artist: "Šako Polumenta" },
  { title: "Kunem ti se zivotom", artist: "Vesna Zmijanac" },
  { title: "Kazni me kazni", artist: "Vesna Zmijanac" },
  { title: "Da zakopčam jeleče", artist: "Zorica Brunclik" },
  { title: "Ja znam da je ljubav", artist: "Zorica Brunclik" },
  { title: "Lido Lidija", artist: "Branka Sovrlić" },
  { title: "Mutivoda", artist: "Sanja Đorđević" },
];

const zaMladozenjaPrimary = [
  { title: "Danas majko ženiš svoga sina", artist: "Slavko Petrović" },
  { title: "Svadba, svadba", artist: "Dragoslav Mihajlović Kanarinac" },
  { title: "Svatovska pjesma", artist: "Goci Bend" },
  { title: "Srećna ti svadba, brate", artist: "Milivoje Karaklajić" },
  { title: "Kume brate", artist: "Šaban Šaulić" },
  { title: "Pevajte pesmu, brat mi se ženi", artist: "Milivoje Karaklajić" },
  { title: "Momak veseljak", artist: "Marinko Rokvić" },
  { title: "Bio sam pijanac", artist: "Šaban Šaulić" },
  { title: "S namerom dođoh u veliki grad", artist: "Šaban Šaulić" },
  { title: "Nismo više tako mladi", artist: "Šaban Šaulić" },
  { title: "Sve ću dati kuću konje", artist: "Šaban Šaulić" },
  { title: "Ti si lek za moju dušu", artist: "Šaban Šaulić" },
  { title: "Naviko sam ja na noćni život", artist: "Toma Zdravković" },
  { title: "Ostao sam sam", artist: "Toma Zdravković" },
  { title: "Dotako sam dno života", artist: "Toma Zdravković" },
  { title: "Kiša je padala", artist: "Toma Zdravković" },
  { title: "Rađaj sinove", artist: "Džej" },
  { title: "99 žena", artist: "Džej" },
  { title: "Imati pa nemati", artist: "Džej" },
  { title: "Ja stalno pijem", artist: "Đani" },
  { title: "Sam sam", artist: "Đani" },
  { title: "Zbog tvojih golih kolena", artist: "Đani" },
  { title: "Stoj Jarane", artist: "Halid Muslimović" },
  { title: "Hej kafano neću više", artist: "Halid Muslimović" },
  { title: "Put putuje moj jaran", artist: "Halid Muslimović" },
  { title: "Bogovi zemljom hode", artist: "Ljuba Aličić" },
  { title: "Dva dobra druga", artist: "Ljuba Aličić" },
  { title: "Skitnica", artist: "Marinko Rokvić" },
  { title: "Koliba il dvor", artist: "Marinko Rokvić" },
  { title: "Potražiću oči nešto zelenije", artist: "Marinko Rokvić" },
  { title: "Zavela me svetla velikoga grada", artist: "Marinko Rokvić" },
  { title: "Vino točim a vino ne pijem", artist: "Miroslav Ilić" },
  { title: "Naljutićeš me ti", artist: "Miroslav Ilić" },
  { title: "Lažu da vreme leči sve", artist: "Miroslav Ilić" },
  { title: "Rastanka se našeg sećam", artist: "Miroslav Ilić" },
  { title: "Ne diraj onog čoveka za stolom", artist: "Mitar Mirić" },
  { title: "Palim zadnju cigaretu", artist: "Mitar Mirić" },
  { title: "Voli me danas vise nego juce", artist: "Mitar Mirić" },
  { title: "Ne znam ja da muški poginem", artist: "Saša Matić" },
  { title: "Nije ovo moja noć", artist: "Saša Matić" },
  { title: "Ne mogu bez tebe vise", artist: "Slavisa Vujic" },
  { title: "Crna golubice", artist: "Slavisa Vujic" },
  { title: "Eh kad bi ti", artist: "Šako Polumenta" },
  { title: "U ljubavi svi su grešni", artist: "Šako Polumenta" },
  { title: "Bato bre", artist: "Indy" },
  { title: "Bio mi je dobar drug", artist: "Narodna" },
  { title: "Ciganima srce daću", artist: "Boban Zdravković" },
  { title: "Ja baraba a ti vila", artist: "Black Panters" },
  { title: "Volim moke koji piju rakiju", artist: "Viki" },
  { title: "Crno na belo", artist: "Viki" },
];

const zaVencanjePrimary = [
  { title: "Polomiću čaše od kristala", artist: "Miroslav Ilić" },
  { title: "Hvala ti za ljubav", artist: "Šaban Šaulić" },
  { title: "Ova svadba najbolja u selu", artist: "Jerina Jović" },
  { title: "Šampionska svadba", artist: "Narodna" },
  { title: "Bravo mlada, šećeru", artist: "Vera Matović" },
  { title: "Rekla nana da mi daš", artist: "Snežana Đurišić" },
  { title: "Leno, Leno, Magdaleno", artist: "Tozovac" },
  { title: "Dajte mi vina", artist: "Narodna" },
  { title: "Dajte vina hoću lom", artist: "Haris" },
  { title: "Muštuluk", artist: "Haris" },
  { title: "Jesul dunje procvale", artist: "Haris" },
  { title: "Oko moje sanjivo", artist: "Narodna" },
  { title: "Mili moj", artist: "Narodna" },
  { title: "Prsten i zlatni lanac", artist: "Narodna" },
  { title: "Zeni nam se vukota", artist: "Narodna" },
  { title: "Mi plešemo", artist: "Narodna" },
  { title: "Hajde da ludujemo ove noći", artist: "Narodna" },
  { title: "Kad zamirišu jorgovani", artist: "Narodna" },
  { title: "Đurđevdan", artist: "Bijelo Dugme" },
  { title: "Lipe cvatu", artist: "Bijelo Dugme" },
  { title: "Zenica bluz", artist: "Bijelo Dugme" },
  { title: "Čardaš", artist: "Narodna" },
  { title: "Dođi u pet do pet", artist: "Narodna" },
  { title: "Suada", artist: "Narodna" },
  { title: "Ringišpil", artist: "Crni Biseri" },
  { title: "Brazil", artist: "Crni Biseri" },
  { title: "Zbog jedne divne crne žene", artist: "Crni Biseri" },
  { title: "Dete sreće", artist: "Marko Bulat" },
  { title: "Eno dole u kafani", artist: "Marko Bulat" },
  { title: "Kraljice moga srca", artist: "Šaban Šaulić" },
  { title: "Golubica", artist: "Šaban Šaulić" },
  { title: "Dva galeba bela", artist: "Šaban Šaulić" },
  { title: "Hajde srećo moja zakuni se ti", artist: "Šaban Šaulić" },
  { title: "Meni je stobom sreca obecana", artist: "Šaban Šaulić" },
  { title: "Hej lepoto nad lepotom", artist: "Šaban Šaulić" },
  { title: "Dajte mi da živim", artist: "Mitar Mirić" },
  { title: "Živela, živela ljubav", artist: "Mitar Mirić" },
  { title: "Jednom kad se zaljubiš", artist: "Mitar Mirić" },
  { title: "Ne može nam niko ništa", artist: "Mitar Mirić" },
  { title: "Kafanska pevačica", artist: "Željko Samardžić" },
  { title: "Sve je moje tvoje", artist: "Željko Samardžić" },
  { title: "Slutim", artist: "Željko Samardžić" },
  { title: "Bezobrazno su zelene", artist: "Željko Samardžić" },
  { title: "Veseljak", artist: "Ana Bekuta" },
  { title: "Zlatiborske zore", artist: "Ana Bekuta" },
  { title: "Brojanica", artist: "Ana Bekuta" },
  { title: "Bekrija", artist: "Ana Bekuta" },
  { title: "Miki Mićo", artist: "Brena" },
  { title: "Mile voli disko", artist: "Brena" },
  { title: "Čik pogodi", artist: "Brena" },
];

const zaKrstenjePrimary = [
  { title: "Srećno ti krštenje", artist: "Mile Nikolić" },
  { title: "Krštenje se danas slavi", artist: "Narodna" },
  { title: "Dva galeba bela", artist: "Šaban Šaulić" },
  { title: "Krštenje", artist: "Vesna Rivas" },
  { title: "Kumovi su došli ime da ti daju", artist: "Mile Nikolić" },
  { title: "Bog je veliki", artist: "Narodna" },
  { title: "Anđeo čuvar", artist: "Narodna" },
  { title: "Mali anđeo", artist: "Narodna" },
  { title: "Blagoslov nebeski", artist: "Narodna" },
  { title: "Sveti Nikola", artist: "Narodna" },
  { title: "Božić je", artist: "Narodna" },
  { title: "Tiho noći", artist: "Narodna" },
  { title: "Dve ruže", artist: "Narodna" },
  { title: "Tri jabuke", artist: "Narodna" },
  { title: "Dete moje", artist: "Narodna" },
  { title: "Mala duša", artist: "Narodna" },
  { title: "Kum i kuma", artist: "Narodna" },
  { title: "Kumovska pesma", artist: "Narodna" },
  { title: "Srećan put dete", artist: "Narodna" },
  { title: "Nebo je blizu", artist: "Narodna" },
  { title: "Molitva za dete", artist: "Narodna" },
  { title: "Krst na čelu", artist: "Narodna" },
  { title: "Voda sveta", artist: "Narodna" },
  { title: "Crkveni zvono", artist: "Narodna" },
  { title: "Porodična radost", artist: "Narodna" },
  { title: "Bela golubica", artist: "Narodna" },
  { title: "Nebeski dom", artist: "Narodna" },
  { title: "Srećno dete", artist: "Narodna" },
  { title: "Kumstvo je sveto", artist: "Narodna" },
  { title: "Ime deteta", artist: "Narodna" },
  { title: "Radost u domu", artist: "Narodna" },
  { title: "Porodica je blago", artist: "Narodna" },
  { title: "Mala ruka", artist: "Narodna" },
  { title: "Prvi koraci", artist: "Narodna" },
  { title: "Srećan dan krštenja", artist: "Narodna" },
  { title: "Kum je drug", artist: "Narodna" },
  { title: "Kuma je sestra", artist: "Narodna" },
  { title: "Blagoslovio Bog", artist: "Narodna" },
  { title: "Nebeski anđeo", artist: "Narodna" },
  { title: "Dete nam se rodilo", artist: "Narodna" },
  { title: "Srećno krštenje dete", artist: "Narodna" },
  { title: "Kumovi došli", artist: "Narodna" },
  { title: "Veselo krštenje", artist: "Narodna" },
  { title: "Porodična sreća", artist: "Narodna" },
  { title: "Mala dušica", artist: "Narodna" },
  { title: "Božji dar", artist: "Narodna" },
  { title: "Sveti krst", artist: "Narodna" },
  { title: "Kumov zalog", artist: "Narodna" },
  { title: "Radost roditelja", artist: "Narodna" },
  { title: "Dete je blago", artist: "Narodna" },
];

const zaRodjenjeCerkePrimary = [
  { title: "Ti si ćerko tatin sin", artist: "Neno" },
  { title: "Devojčice moja mila", artist: "Verica Šerifović" },
  { title: "Imam ćerku lepoticu", artist: "Aco Aličić" },
  { title: "Plavokosa devojčica", artist: "Narodna" },
  { title: "Pepeljuga", artist: "Verica Šerifović" },
  { title: "Ćero moja mila", artist: "Nada Topčagić" },
  { title: "Mala princeza", artist: "Narodna" },
  { title: "Ćerka tatinog srca", artist: "Narodna" },
  { title: "Rođena je ćerka", artist: "Narodna" },
  { title: "Moja mala devojčica", artist: "Narodna" },
  { title: "Plava kosa", artist: "Narodna" },
  { title: "Ćerka mi se rodila", artist: "Narodna" },
  { title: "Tatin sin ćerka", artist: "Neno" },
  { title: "Devojčica mala", artist: "Narodna" },
  { title: "Moja princeza", artist: "Narodna" },
  { title: "Ćerka je blago", artist: "Narodna" },
  { title: "Rođena devojčica", artist: "Narodna" },
  { title: "Mala ćerka", artist: "Narodna" },
  { title: "Tata i ćerka", artist: "Narodna" },
  { title: "Mama i ćerka", artist: "Narodna" },
  { title: "Ćerka mojih snova", artist: "Narodna" },
  { title: "Devojčica sa neba", artist: "Narodna" },
  { title: "Mala ruža", artist: "Narodna" },
  { title: "Ćerka tatinog doma", artist: "Narodna" },
  { title: "Rođena je devojčica", artist: "Narodna" },
  { title: "Moja ćerka", artist: "Narodna" },
  { title: "Ćerka moga srca", artist: "Narodna" },
  { title: "Devojčica moje majke", artist: "Narodna" },
  { title: "Mala princeza kuće", artist: "Narodna" },
  { title: "Ćerka nam se rodila", artist: "Narodna" },
  { title: "Devojka mala", artist: "Narodna" },
  { title: "Ćerka tatinog sna", artist: "Narodna" },
  { title: "Rođena devojka", artist: "Narodna" },
  { title: "Moja mala ćerka", artist: "Narodna" },
  { title: "Ćerka je dar", artist: "Narodna" },
  { title: "Devojčica u krilu", artist: "Narodna" },
  { title: "Mala devojčica", artist: "Narodna" },
  { title: "Ćerka tatinog života", artist: "Narodna" },
  { title: "Rođena je princeza", artist: "Narodna" },
  { title: "Moja devojčica", artist: "Narodna" },
  { title: "Ćerka moga doma", artist: "Narodna" },
  { title: "Devojčica sa neba", artist: "Verica Šerifović" },
  { title: "Mala ružica", artist: "Narodna" },
  { title: "Ćerka tatinog blaga", artist: "Narodna" },
  { title: "Rođena je mala", artist: "Narodna" },
  { title: "Moja mala princeza", artist: "Narodna" },
  { title: "Ćerka moga života", artist: "Narodna" },
  { title: "Devojčica moga srca", artist: "Narodna" },
  { title: "Mala ćerka tatinog srca", artist: "Narodna" },
  { title: "Ćerka je sreća", artist: "Narodna" },
];

const zaRodjenjeSinaPrimary = [
  { title: "Rodio se sin, mali gospodin", artist: "Nada Topčagić" },
  { title: "Rodio se sin", artist: "Narodna" },
  { title: "Muško mi se rodilo", artist: "Ljuba Aličić" },
  { title: "Sine moj", artist: "Milomir Miljanić Miljan" },
  { title: "Rodila sam sina", artist: "Narodna" },
  { title: "Rodi mi draga sina", artist: "Narodna" },
  { title: "Mali gospodin", artist: "Narodna" },
  { title: "Sin tatinog srca", artist: "Narodna" },
  { title: "Rođen je sin", artist: "Narodna" },
  { title: "Moj sin moj", artist: "Narodna" },
  { title: "Sin mi se rodio", artist: "Narodna" },
  { title: "Mali muškarac", artist: "Narodna" },
  { title: "Sin je blago", artist: "Narodna" },
  { title: "Tatin sin", artist: "Narodna" },
  { title: "Sin moga srca", artist: "Narodna" },
  { title: "Rođen sin", artist: "Narodna" },
  { title: "Mali junak", artist: "Narodna" },
  { title: "Sin tatinog doma", artist: "Narodna" },
  { title: "Muško dete", artist: "Narodna" },
  { title: "Sin moj mali", artist: "Narodna" },
  { title: "Rođen je dečak", artist: "Narodna" },
  { title: "Sin tatinog sna", artist: "Narodna" },
  { title: "Mali gospodine", artist: "Narodna" },
  { title: "Sin je naslednik", artist: "Narodna" },
  { title: "Rođen je naslednik", artist: "Narodna" },
  { title: "Sin moga života", artist: "Narodna" },
  { title: "Mali sin", artist: "Narodna" },
  { title: "Sin tatinog blaga", artist: "Narodna" },
  { title: "Rođen je mali", artist: "Narodna" },
  { title: "Sin moga doma", artist: "Narodna" },
  { title: "Muško mi dete", artist: "Narodna" },
  { title: "Sin tatinog života", artist: "Narodna" },
  { title: "Rođen je sin moj", artist: "Narodna" },
  { title: "Mali gospodin kuće", artist: "Narodna" },
  { title: "Sin je dar", artist: "Narodna" },
  { title: "Rođen dečak", artist: "Narodna" },
  { title: "Sin moga srca mali", artist: "Narodna" },
  { title: "Tatin sin mali", artist: "Narodna" },
  { title: "Sin tatinog imena", artist: "Narodna" },
  { title: "Rođen je sin tatin", artist: "Narodna" },
  { title: "Mali sin tatin", artist: "Narodna" },
  { title: "Sin je sreća", artist: "Narodna" },
  { title: "Rođen sin moj", artist: "Narodna" },
  { title: "Sin tatinog nasledstva", artist: "Narodna" },
  { title: "Mali muškarac kuće", artist: "Narodna" },
  { title: "Sin moga blaga", artist: "Narodna" },
  { title: "Rođen je mali sin", artist: "Narodna" },
  { title: "Sin tatinog srca mali", artist: "Narodna" },
  { title: "Moj sin mali", artist: "Narodna" },
  { title: "Sin je naslednik doma", artist: "Narodna" },
];

const categories = [
  { id: "za-mladu", label: "Za mladu", songs: pick(zaMladuPrimary, weddingPool) },
  { id: "za-mladozenja", label: "Za mladoženja", songs: pick(zaMladozenjaPrimary, weddingPool) },
  { id: "za-vencanje", label: "Za venčanje", songs: pick(zaVencanjePrimary, weddingPool) },
  { id: "za-krstenje", label: "Za krštenje", songs: pick(zaKrstenjePrimary, weddingPool) },
  { id: "za-rodjenje-cerke", label: "Za rođenje ćerke", songs: pick(zaRodjenjeCerkePrimary, weddingPool) },
  { id: "za-rodjenje-sina", label: "Za rođenje sina", songs: pick(zaRodjenjeSinaPrimary, weddingPool) },
];

for (const cat of categories) {
  if (cat.songs.length < 50) {
    console.warn(`Warning: ${cat.id} has only ${cat.songs.length} songs`);
  }
}

const out = `import type { SongCategory } from "./types";

export const songCategories: SongCategory[] = ${JSON.stringify(categories, null, 2)};
`;

fs.writeFileSync(path.join(root, "lib/songs/index.ts"), out, "utf8");
console.log("Generated lib/songs/index.ts");
for (const cat of categories) {
  console.log(`  ${cat.label}: ${cat.songs.length} pesama`);
}
